services:
  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fortune-blazor-wasm
    networks:
      - "proxy-net"
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.fortune.rule=Host(`fortune.home`)'
      - "traefik.http.services.fortune.loadbalancer.server.port=80"
networks:
  proxy-net:
    external: true
    

